const ACTIVE_PASSIVE_SKILL_NAMES = [
  '_3Faith',
  '_Argutus Vita_Telum',
  '_Biolo_Monster_List',
  '_ElementalMaster_spirit',
  '_Meister_ABR_List',
  '_Meister_Quake',
  '_Meister_Rush',
  '_NightWatch_Aiming Count',
  '_Religio_Benedictum',
  '_Trouvere_Troubadour_ignore_res_mres',
  '_Trouvere_Troubadour_pAtk_sMatk',
  '16th Night',
  'Abyss Slayer',
  'Acid Demonstration',
  'Adrenaline Rush',
  'Advanced Book',
  'Advanced Katar Mastery',
  'Arclouse Dash',
  'Ardor',
  'Ardor',
  'Argutus Telum',
  'Argutus Vita',
  'Asir Runestone',
  'Assumptio',
  'Astral Strike',
  'Attack Stance',
  'Aura Blade',
  'Auto Guard',
  'Auto Spell',
  'Axe Mastery',
  'Bash',
  'Basilica',
  'Beast Bane',
  'Benedictum',
  'Bio Cannibalize',
  'Blessing of Moon',
  'Blessing of Star',
  'Blessing of Sun',
  'Break Through',
  'Bunch of Shrimp',
  'Calamity Gale',
  'Camouflage',
  'Cantocandidus',
  'Cart Remodeling',
  'Cart Weight',
  'Cavalier Mastery',
  'Chain Action',
  'Charm',
  'Circling Nature',
  'Clementia',
  'Climax',
  'Cloaking Exceed',
  'Comet Amp',
  'Crazy Uproar',
  'Cross Wound',
  'Current HP',
  'Current SP',
  'Dagger & Bow Mastery',
  'Dagger Throwing Practice',
  'Dance With Wug',
  'Dancing Lesson',
  'Death Bound',
  'Demon Bane',
  'Distorted Crescent',
  'Divine Protection',
  'Divulio',
  'Dodge',
  'Double Attack',
  'Dragon Howling',
  'Dragon Training',
  'Dragonic Aura',
  'Dragonology',
  'Elemental Spirit Mastery',
  'Enchant Blade',
  'Enchant Deadly Poison',
  'Enchanting Shadow',
  'Expiatio',
  'Fairy Soul',
  'Faith',
  'Falcon Eyes',
  'Fear Breeze',
  'Fidus Animus',
  'Fire Earth Research',
  'Foresight',
  'Frash Shrimp',
  'Freezing Spell',
  'Frost Weapon',
  'Fusion of Sun, Moon and Star',
  'Geffenia Nocturne',
  'Gentle Touch - Alive',
  'Gentle Touch - Opposite',
  'Grand Judgement',
  'Gunslinger Mine',
  'Happy Break',
  'Heal',
  'Hiding',
  'Hilt Binding',
  'Holy Shield',
  'Illusion - Bewitch',
  'Illusion - Death',
  'Illusion - Shadow',
  'Illusion - Shock',
  'Impositio Manus',
  'Improve Concentration',
  'Improve Dodge',
  'Increase HP Recovery',
  'Increase SP Recovery',
  'Indulge',
  'Inspiration',
  'Intimidate',
  'Iron Hand',
  'Kaahi',
  'Katar Mastery',
  'Kiling Cloud',
  'Knowledge of Sun Moon and Star',
  'Knowledge of Sun, Moon and Star',
  'Kyrie Eleison',
  'Land Protector',
  'Laudaagnus',
  'Learning Potion',
  'Lefthand Mastery',
  'Lesson',
  'Lightning Loader',
  'Lunar Luminance',
  'Lux Anima Runestone',
  'Mace & Book Mastery',
  'Mace Mastery',
  'Madogear License',
  'Maelstrom',
  'Magic Book Mastery',
  'Magic Sword Mastery',
  'Magnificat',
  'Main Ranger',
  'March of Prontera',
  'Meditation',
  'Meow Meow',
  'Moonlight Fantasy',
  'Moonlight Serenade',
  'Musical Lesson',
  'Mystic Symphony',
  'Neutral Barrier',
  'New Poison Research',
  'Ninja Aura',
  'Ninja Mastery',
  'Offertorium',
  'On Magogear',
  'Peaceful Break',
  'Piety',
  'Plagiarism',
  'Platinum Altar',
  'Poisonous Weapon',
  'Potent Venom',
  'Power Maximize',
  'Power of Flock',
  'Power of Land',
  'Power of Life',
  'Power of Sea',
  'Power Thrust',
  'Power',
  'Presens Acies',
  'Preserve',
  'Procella',
  'Pure Soul',
  'Pyroclastic',
  'Radius',
  'Recognized Spell',
  'Released',
  'Religio',
  'Reproduce',
  'Rhapsody of Mineworker',
  'Ride Dragon',
  'Ride Peco',
  'Righthand Mastery',
  'Rising Dragon',
  'Run',
  'Rune Mastery',
  'Rush To Windmill',
  'Safety Wall',
  'Scratch',

  'Seismic Weapon',
  'Serenade of Jawaii',
  'Serpens',
  'Seven Wind',
  'Shadow Exceed',
  'Shadow Formation',
  'Shadow Sense',
  'Shadow Spell',
  'Shadow Warrior',
  'Shadow Wound',
  'Shield Mastery',
  'Shield Spell',
  'Silvervine Root Twist',
  'Single Action',
  'Skin Tempering',
  'Snake Eyes',
  'Snatcher',
  'P.F.I.',
  'Intensive Aim',
  'Grenade Fragment',

  'Solar Luminance',
  'Solar Stance',
  'Song Of Mana',
  'Soul Cutter',
  'Soul Drain',
  'Soul',
  'Spear & Sword Mastery',
  'Spear Dynamo',
  'Spear Mastery',
  'Spear Quicken',
  'Spell Enchanting',
  'Spin Count',
  'Sprit Of Life',
  'Stage Manner',
  'Steel Crow',
  'Stellar Luminance',
  'Stellar Stance',
  'Striking',
  'Strip Shadow',
  'Swing Dance',
  'Sword Mastery',
  'Terramotus',
  'Grenade Mastery',
  'Total Soul',
  'Total Spirit',
  'Transcendence',
  'Trap Research',
  'Turisus Runestone',
  'Two Hand Defending',
  'Two hand Quicken',
  'Two hand Staff Mastery',
  'Hidden Card',
  'Two-Handed Sword Mastery',
  'Venom Impression',
  'Vigor condensation',
  'Vigor Explosion',
  'Weapon Blocking',
  'Weapon Perfection',
  'Weaponry Research',
  'Will of Faith',
  'Wind Walk',
  'Wooden Fairy',
  'Wounding Shot',
  'Wrath of',
  'Wug Rider',
  "Bragi's Poem",
  "Frigg's Song",
  "Lerad's Dew",
  "Odin's Power",
  "Owl's Eye",
  "Vulture's Eye",
] as const;

export const OFFENSIVE_SKILL_NAMES = [
  'Acid Bomb',
  'Acid Terror',
  'Adoramus',
  'Aimed Bolt',
  'Anti-Material Blast',
  'Arm Cannon',
  'Arrow Shower',
  'Arrow Storm',
  'Arrow Vulcan',
  'Axe Boomerang',
  'Tornado Storm',
  'Axe Tornado',
  'Back Stab',
  'Banishing Point',
  'Blaze Kick',
  'Blitz Beat',
  'Bomb Cluster',
  'Bowling Bash',
  'Intensification',
  'Brandish Spear',
  'Burst Attack',
  'Cannon Spear',
  'Cart Boost',
  'Cart Cannon',
  'Cart Revolution',
  'Cart Termination',
  'Cart Tornado',
  'Catnip Meteor',
  'Chain Combo',
  'Chain Crush Combo',
  'Chain Lightning',
  'Chattering',
  'Clashing Spiral',
  'Claymore Trap',
  'Cold Bolt',
  'Cold Slower',
  'Combo Finish',
  'Comet',
  'Counter Slash',
  'Crazy Weed',
  'Crescive Bolt',
  'cri_race_demon',
  'cri_race_dragon',
  'cri_race_fish',
  'cri_race_insect',
  'cri_race_undead',
  'Crimson Marker',
  'Crimson Rock',
  'Cross Impact',
  'Cross Ripper Slasher',
  'Rain of Crystal',
  'Cross Slash',
  'Curse Explosion',
  'Dark Claw',
  'Dark Illusion',
  'Dart Arrow',
  'Desperado',
  'Fatal Shadow Claw',
  'Diamond Dust',
  'Wind Cutter',
  'dmg__Lucifer Morocc',
  'Double Strafe',
  'Dragon Breath - WATER',
  'Rock Down',
  'Dragon Breath',
  'Eternal Slash',
  'Soul Vulcan Strike',
  'Dragon Combo',
  'Dragon Tail',
  'Drain Life',
  'Rush Quake',
  'Duple Light',
  'Earth Drive',
  'Earth Grave',
  'Earth Shaker',
  'Earth Spike',
  'Earth Strain',
  'Envenom',
  'Esma',
  'Mystery Illusion',
  'Espa',
  'Eswhoo',
  'Evil Soul Curse',
  'Exploding Dragon',
  'Fallen Empire',
  'Falling Stars',
  'Fatal Manace',
  'Moon Slasher',
  'Feint Bomb',
  'Finger Offensive',
  'Fire Ball',
  'Abyss Dagger',
  'Fire Bolt',
  'Fire Dance',
  'Fire Pillar',
  'Fire Rain',
  'Firewall',
  'Shadow Stab',
  'Explosion Blaster',
  'Crimson Arrow',
  'First Wind',
  'Frozen Slash',
  'Flame Launcher',
  'Flaming Petals',
  'Flash Combo',
  'Flash Kick',
  'Focused Arrow Strike',
  'Fist Spell',
  'Freezing Spear',
  'Frost Misty',
  'Full Blast',
  'Full Moon Kick',
  'Genesis Ray',
  'Gloria Domini',
  'Grand Cross',
  'Gravitational Field',
  'Great Echo',
  'Grimtooth',
  'First Brand',
  'Hell Gate',
  'Hell Inferno',
  'Hell Plant',
  'Hiss',
  'Holy Cross',
  'Holy Light',
  'Hot Barrel',
  'Howling Mine',
  'Deft Stab',
  'Hundred Spears',
  'Storm Cannon',
  'Ignition Break',
  'Infiltration',
  'Arbitrium',
  'Jack Frost',
  'Judex',
  'Frost Nova',
  'Jupitel Thunder',
  'Killing Cloud',
  'Shield Shooting',
  'Frenzy Shot',
  'Knuckle Arrow',
  'Knuckle Boost',
  'Kunai Explosion',
  'Kunai Splash',
  'Storm Slash',
  'Land Mine',
  'Lava Flow',
  'Second Faith',
  'Chain Reaction Shot',
  'Omega Abyss Strike',
  'Framen',
  'Diamond Storm',
  'Lightening Bolt',
  'Lightning Ride',
  'Conflagration',
  'Cross Rain',
  'Lion Howling',
  'Lord of Vermilion',
  'Lucky Cast',
  'Lunatic Carrot Beat',
  'Magnum Break',
  'Magnus Exorcismus',
  'Savage Impact',
  'Mammonite',
  'Unlucky Rush',
  'Mandragora Howling',
  'Hack and Slasher',
  'Masquerade-Enervation',
  'Masquerade-Groomy',
  'Masquerade-Weakness',
  'Elemental Buster',
  'Mass Spiral',
  'Metalic Sound',
  'Meteor Assault',
  'Second Flame',
  'Second Judgement',
  'Meteor Storm',
  'Musical Strike',
  'Mystical Amplification',
  'Napalm Beat',
  'Massive Flame Blaster',
  'Napalm Vulcan',
  'New Moon Kick',
  'No Limits',
  'Nuckle Boost',
  'Nyang Grass',
  'Oratio',
  'Over Brand',
  'Picky Peck',
  'Pierce',
  'Pile Bunker',
  'Poison Burst',
  'Power Absorb',
  'Power Swing',
  'Venom Swamp',
  'Psychic Wave',
  'Quick Draw Shot',
  'Terra Drive',
  'Raid',
  'Madness Crusher',
  'Rampage Blast',
  'Reverberation',
  'Rolling Cutter',
  'Round Trip',
  'Scar of Tarou',
  'Severe Rainstorm',
  'Shatter Storm',
  'Shield Boomerang',
  'Shield Chain',
  'Shield Press',
  'Spirit of Savage',
  'Sightless Mind',
  'Silvervine Stem Spear',
  'Sky Blow',
  'Slinging Arrow',
  'Slug Shot',
  'Snow Flake Draft',
  'Solar Explosion',
  'Sonic Blow',
  'Sonic Wave',
  'Soul Destroyer',
  'Soul Expansion',
  'Soul Harvest',
  'Soul Strike',
  'Spore Explosion',
  'Spread Shot',
  'Sprit Of Savage',
  'Storm Blast',
  'Storm Gust',
  'Suicidal Destruction',
  'Swirling Petal',
  'Tasty Shrimp Party',
  'Tetra Vortex',
  'Throw Huuma Shuriken',
  'Throw Kunai',
  'Thunderstorm',
  'Tiger Cannon',
  'Tornado Axe',
  'Triangle Shot',
  'Turn Undead',
  'Urgent Escape',
  'Vanishing Buster',
  'Varetyr Spear',
  'Vulcan Arm',
  'Warmer',
  'Water Insignia',
  'Wind Blade',
  'Third Consecration',
  'Oleum Sanctum',
  "Flame Trap",
  "Solid Trap",
  "Deep Blind Trap",
  "Switf Trap",
  "Swift Trap",
  "Sound Blend",
  'Rhythm Shooting',
  'Third Flame Bomb',
  'Third Punish',
  'Wug Strike',
  "God's Hammer",
  'Overslash',
  "Heaven's Drive",
  'Lightning Land',
  'Floral Flare Road',
  "Rich's Coin",
  'Stratum Tremor',
  'Petitio',
  'Gale Storm',
  'Acidified Zone Fire',
  'Acidified Zone Water',
  'Acidified Zone Wind',
  'Acidified Zone Earth',
  'Servant Weapon',
  'From the Abyss',
  'Axe Stomp',
  'Impact Crater',
  'Hesperus Lit',
  'The Vigilante at Night',
  'Only One Bullet',
  'Spiral Shooting',
  'Magazine for One',
  'Wild Fire',
  'Basic Grenade',
  'Hasty Fire in the Hole',
  'Grenade Dropping',
  'Mission Bombard',
  'Wild Shot',
  'Midnight Fallen',

  // 4th in the future
  "Abyss Square",
  "Activation Attack Machine",
  "Chulho Sonic Claw",
  "Howling of Chulho",
  "Cold Blooded Cannon",
  "Darkening Cannon",
  "Dawn Break",
  "Double Bowling Bash",
  "Dragonic Breath",
  "Exorcism of Malicious Soul",
  "Explosive Powder",
  "Golden Dragon Cannon",
  "Ground Gravitation",
  "Flamen",
  "Crystal Impact",
  "Hohogong Strike",
  "Hawk Boomerang",
  "Hawk Rush",
  "Hell's Drive",
  "Hogogong Strike",
  "Huuma Shuriken - Construct",
  "Huuma Shuriken - Grasp",
  "Hyunrok Breeze",
  "Hyunrok Cannon",
  "Jack Frost Nova",
  "Jupitel Thunderstorm",
  "Kunai - Distortion",
  "Kunai - Refraction",
  "Kunai - Rotation",
  "Mayhemic Thorns",
  "Mega Sonic Blow",
  "Metallic Fury",
  "Meteor Storm Buster",
  "Midnight Kick",
  "Mighty Smash",
  "Noon Blast",
  "Red Flame Cannon",
  "Rose Blossom",
  "Shadow Dance",
  "Shadow Flash",
  "Shield Chain Rush",
  "Spark Blaster",
  "Napalm Vulcan Strike",
  "Spiral Pierce Max",
  "Star Cannon",
  "Sunset Blast",
  "Talisman of Black Tortoise",
  "Talisman of Blue Dragon",
  "Talisman of Red Phoenix",
  "Talisman of White Tiger",
  "Talisman of Soul Stealing",
  "Talisman of Four Bearing God",
  "Thundering Cannon",
  "Triple Laser",
  "Rising Sun",
  "Rapid Smiting",
  "Twinkling Galaxy",
  "Warg Strike",
] as const;

const dup = [];
for (const s of ACTIVE_PASSIVE_SKILL_NAMES) {
  if (OFFENSIVE_SKILL_NAMES.includes(s as any)) {
    dup.push(s);
  }
}

if (dup.length > 0) console.log('skillname_dupplicates', dup);

export type SKILL_NAME = (typeof ACTIVE_PASSIVE_SKILL_NAMES)[number] | (typeof OFFENSIVE_SKILL_NAMES)[number];
