const activePassiveSkillName = [
  '_3Faith',
  '_Argutus Vita_Telum',
  '_Biolo_Monster_List',
  '_ElementalMaster_spirit',
  '_Meister_ABR_List',
  '_Meister_Quake',
  '_Meister_Rush',
  '_NightWatch_Aiming Count',
  '_Religio_Benedictum',
  '_Trouvere_Troubadour_ignore_res_mres',
  '_Trouvere_Troubadour_pAtk_sMatk',
  '16th Night',
  'Abyss Dagger',
  'Abyss Slayer',
  'Acid Demonstration',
  'Adrenaline Rush',
  'Advanced Book',
  'Advanced Katar Mastery',
  'Arbitrium',
  'Arclouse Dash',
  'Ardor',
  'Ardor',
  'Argutus Telum',
  'Argutus Vita',
  'Asir Runestone',
  'Assumptio',
  'Astral Strike',
  'Attack Stance',
  'Aura Blade',
  'Auto Guard',
  'Auto Spell',
  'Axe Mastery',
  'Bash',
  'Basilica',
  'Beast Bane',
  'Benedictum',
  'Bio Cannibalize',
  'Blessing of Moon',
  'Blessing of Star',
  'Blessing of Sun',
  'Break Through',
  'Bunch of Shrimp',
  'Calamity Gale',
  'Camouflage',
  'Cantocandidus',
  'Cart Remodeling',
  'Cart Weight',
  'Cavalier Mastery',
  'Chain Action',
  'Chain Reaction Shot',
  'Charm',
  'Circling Nature',
  'Clementia',
  'Climax',
  'Cloaking Exceed',
  'Comet Amp',
  'Conflagration',
  'Crazy Uproar',
  'Crimson Arrow',
  'Cross Rain',
  'Cross Wound',
  'Current HP',
  'Current SP',
  'Dagger & Bow Mastery',
  'Dagger Throwing Practice',
  'Dance With Wug',
  'Dancing Lesson',
  'Death Bound',
  'Deft Stab',
  'Demon Bane',
  'Diamond Storm',
  'Distorted Crescent',
  'Divine Protection',
  'Divulio',
  'Dodge',
  'Double Attack',
  'Dragon Howling',
  'Dragon Training',
  'Dragonic Aura',
  'Dragonology',
  'Elemental Buster',
  'Elemental Spirit Mastery',
  'Enchant Blade',
  'Enchant Deadly Poison',
  'Enchanting Shadow',
  'Eternal Slash',
  'Expiatio',
  'Explosion Blaster',
  'Fairy Soul',
  'Faith',
  'Falcon Eyes',
  'Fatal Shadow Claw',
  'Fear Breeze',
  'Fidus Animus',
  'Fire Earth Research',
  'First Brand',
  'Fist Spell',
  'Foresight',
  'Framen',
  'Frash Shrimp',
  'Freezing Spell',
  'Frenzy Shot',
  'Frost Weapon',
  'Frozen Slash',
  'Fusion of Sun, Moon and Star',
  'Geffenia Nocturne',
  'Gentle Touch - Alive',
  'Gentle Touch - Opposite',
  'Grand Judgement',
  'Gunslinger Mine',
  'Hack and Slasher',
  'Happy Break',
  'Heal',
  'Hiding',
  'Hilt Binding',
  'Holy Shield',
  'Illusion - Bewitch',
  'Illusion - Death',
  'Illusion - Shadow',
  'Illusion - Shock',
  'Impositio Manus',
  'Improve Concentration',
  'Improve Dodge',
  'Increase HP Recovery',
  'Increase SP Recovery',
  'Indulge',
  'Inspiration',
  'Intensification',
  'Intimidate',
  'Iron Hand',
  'Kaahi',
  'Katar Mastery',
  'Kiling Cloud',
  'Knowledge of Sun Moon and Star',
  'Knowledge of Sun, Moon and Star',
  'Kyrie Eleison',
  'Land Protector',
  'Laudaagnus',
  'Learning Potion',
  'Lefthand Mastery',
  'Lesson',
  'Lightning Loader',
  'Lunar Luminance',
  'Lux Anima Runestone',
  'Mace & Book Mastery',
  'Mace Mastery',
  'Madness Crusher',
  'Madogear License',
  'Maelstrom',
  'Magic Book Mastery',
  'Magic Sword Mastery',
  'Magnificat',
  'Main Ranger',
  'March of Prontera',
  'Massive Flame Blaster',
  'Meditation',
  'Meow Meow',
  'Moon Slasher',
  'Moonlight Fantasy',
  'Moonlight Serenade',
  'Musical Lesson',
  'Mystery Illusion',
  'Mystic Symphony',
  'Neutral Barrier',
  'New Poison Research',
  'Ninja Aura',
  'Ninja Mastery',
  'Offertorium',
  'Oleum Sanctum',
  'Omega Abyss Strike',
  'On Magogear',
  'Peaceful Break',
  'Piety',
  'Plagiarism',
  'Platinum Altar',
  'Poisonous Weapon',
  'Potent Venom',
  'Power Maximize',
  'Power of Flock',
  'Power of Land',
  'Power of Life',
  'Power of Sea',
  'Power Thrust',
  'Power',
  'Presens Acies',
  'Preserve',
  'Procella',
  'Pure Soul',
  'Pyroclastic',
  'Radius',
  'Rain of Crystal',
  'Recognized Spell',
  'Released',
  'Religio',
  'Reproduce',
  'Rhapsody of Mineworker',
  'Ride Dragon',
  'Ride Peco',
  'Righthand Mastery',
  'Rising Dragon',
  'Rock Down',
  'Run',
  'Rune Mastery',
  'Rush Quake',
  'Rush To Windmill',
  'Safety Wall',
  'Savage Impact',
  'Scratch',
  'Second Faith',
  'Second Flame',
  'Second Judgement',
  'Seismic Weapon',
  'Serenade of Jawaii',
  'Serpens',
  'Seven Wind',
  'Shadow Exceed',
  'Shadow Formation',
  'Shadow Sense',
  'Shadow Spell',
  'Shadow Stab',
  'Shadow Warrior',
  'Shadow Wound',
  'Shield Mastery',
  'Shield Shooting',
  'Shield Spell',
  'Silvervine Root Twist',
  'Single Action',
  'Skin Tempering',
  'Snake Eyes',
  'Snatcher',
  'P.F.I.',
  'Intensive Aim',
  'Grenade Fragment',

  'Solar Luminance',
  'Solar Stance',
  'Song Of Mana',
  'Soul Cutter',
  'Soul Drain',
  'Soul Vulcan Strike',
  'Soul',
  'Spear & Sword Mastery',
  'Spear Dynamo',
  'Spear Mastery',
  'Spear Quicken',
  'Spell Enchanting',
  'Spin Count',
  'Spirit of Savage',
  'Sprit Of Life',
  'Stage Manner',
  'Steel Crow',
  'Stellar Luminance',
  'Stellar Stance',
  'Storm Cannon',
  'Storm Slash',
  'Striking',
  'Strip Shadow',
  'Swing Dance',
  'Sword Mastery',
  'Terra Drive',
  'Terramotus',
  'Grenade Mastery',
  'Tornado Storm',
  'Total Soul',
  'Total Spirit',
  'Transcendence',
  'Trap Research',
  'Turisus Runestone',
  'Two Hand Defending',
  'Two hand Quicken',
  'Two hand Staff Mastery',
  'Hidden Card',
  'Two-Handed Sword Mastery',
  'Unlucky Rush',
  'Venom Impression',
  'Venom Swamp',
  'Vigor condensation',
  'Vigor Explosion',
  'Weapon Blocking',
  'Weapon Perfection',
  'Weaponry Research',
  'Will of Faith',
  'Wind Walk',
  'Wooden Fairy',
  'Wounding Shot',
  'Wrath of',
  'Wug Rider',
  "Bragi's Poem",
  "Frigg's Song",
  "Lerad's Dew",
  "Odin's Power",
  "Owl's Eye",
  "Vulture's Eye",
] as const;

export const OFFENSIVE_SKILL_NAMES = [
  'Acid Bomb',
  'Acid Terror',
  'Adoramus',
  'Aimed Bolt',
  'Anti-Material Blast',
  'Arm Cannon',
  'Arrow Shower',
  'Arrow Storm',
  'Arrow Vulcan',
  'Axe Boomerang',
  'Axe Tornado',
  'Back Stab',
  'Banishing Point',
  'Blaze Kick',
  'Blitz Beat',
  'Bomb Cluster',
  'Bowling Bash',
  'Brandish Spear',
  'Burst Attack',
  'Cannon Spear',
  'Cart Boost',
  'Cart Cannon',
  'Cart Revolution',
  'Cart Termination',
  'Cart Tornado',
  'Catnip Meteor',
  'Chain Combo',
  'Chain Crush Combo',
  'Chain Lightning',
  'Chattering',
  'Clashing Spiral',
  'Claymore Trap',
  'Cold Bolt',
  'Cold Slower',
  'Combo Finish',
  'Comet',
  'Counter Slash',
  'Crazy Weed',
  'Crescive Bolt',
  'cri_race_demon',
  'cri_race_dragon',
  'cri_race_fish',
  'cri_race_insect',
  'cri_race_undead',
  'Crimson Marker',
  'Crimson Rock',
  'Cross Impact',
  'Cross Ripper Slasher',
  'Cross Slash',
  'Curse Explosion',
  'Dark Claw',
  'Dark Illusion',
  'Dart Arrow',
  'Desperado',
  'Diamond Dust',
  'dmg__Lucifer Morocc',
  'Double Strafe',
  'Dragon Breath - WATER',
  'Dragon Breath',
  'Dragon Combo',
  'Dragon Tail',
  'Drain Life',
  'Duple Light',
  'Earth Drive',
  'Earth Grave',
  'Earth Shaker',
  'Earth Spike',
  'Earth Strain',
  'Envenom',
  'Esma',
  'Espa',
  'Eswhoo',
  'Evil Soul Curse',
  'Exploding Dragon',
  'Fallen Empire',
  'Falling Stars',
  'Fatal Manace',
  'Feint Bomb',
  'Finger Offensive',
  'Fire Ball',
  'Fire Bolt',
  'Fire Dance',
  'Fire Pillar',
  'Fire Rain',
  'Firewall',
  'First Wind',
  'Flame Launcher',
  'Flaming Petals',
  'Flash Combo',
  'Flash Kick',
  'Focused Arrow Strike',
  'Freezing Spear',
  'Frost Misty',
  'Full Blast',
  'Full Moon Kick',
  'Genesis Ray',
  'Gloria Domini',
  'Grand Cross',
  'Gravitational Field',
  'Great Echo',
  'Grimtooth',
  'Hell Gate',
  'Hell Inferno',
  'Hell Plant',
  'Hiss',
  'Holy Cross',
  'Holy Light',
  'Hot Barrel',
  'Howling Mine',
  'Hundred Spears',
  'Ignition Break',
  'Infiltration',
  'Jack Frost',
  'Judex',
  'Jupitel Thunder',
  'Killing Cloud',
  'Knuckle Arrow',
  'Knuckle Boost',
  'Kunai Explosion',
  'Kunai Splash',
  'Land Mine',
  'Lava Flow',
  'Lightening Bolt',
  'Lightning Ride',
  'Lion Howling',
  'Lord of Vermilion',
  'Lucky Cast',
  'Lunatic Carrot Beat',
  'Magnum Break',
  'Magnus Exorcismus',
  'Mammonite',
  'Mandragora Howling',
  'Masquerade-Enervation',
  'Masquerade-Groomy',
  'Masquerade-Weakness',
  'Mass Spiral',
  'Metalic Sound',
  'Meteor Assault',
  'Meteor Storm',
  'Musical Strike',
  'Mystical Amplification',
  'Napalm Beat',
  'Napalm Vulcan',
  'New Moon Kick',
  'No Limits',
  'Nuckle Boost',
  'Nyang Grass',
  'Oratio',
  'Over Brand',
  'Picky Peck',
  'Pierce',
  'Pile Bunker',
  'Poison Burst',
  'Power Absorb',
  'Power Swing',
  'Psychic Wave',
  'Quick Draw Shot',
  'Raid',
  'Rampage Blast',
  'Reverberation',
  'Rolling Cutter',
  'Round Trip',
  'Savage Of Spirit',
  'Scar of Tarou',
  'Severe Rainstorm',
  'Shatter Storm',
  'Shield Boomerang',
  'Shield Chain',
  'Shield Press',
  'Sightless Mind',
  'Silvervine Stem Spear',
  'Sky Blow',
  'Slinging Arrow',
  'Slug Shot',
  'Snow Flake Draft',
  'Solar Explosion',
  'Sonic Blow',
  'Sonic Wave',
  'Soul Destroyer',
  'Soul Expansion',
  'Soul Harvest',
  'Soul Strike',
  'Spore Explosion',
  'Spread Shot',
  'Sprit Of Savage',
  'Storm Blast',
  'Storm Gust',
  'Suicidal Destruction',
  'Swirling Petal',
  'Tasty Shrimp Party',
  'Tetra Vortex',
  'Throw Huuma Shuriken',
  'Throw Kunai',
  'Thunderstorm',
  'Tiger Cannon',
  'Tornado Axe',
  'Triangle Shot',
  'Turn Undead',
  'Urgent Escape',
  'Vanishing Buster',
  'Varetyr Spear',
  'Vulcan Arm',
  'Warmer',
  'Water Insignia',
  'Wind Blade',
  'Wind Cutter',
  'Third Consecration',
  'Rhythm Shooting',
  'Third Flame Bomb',
  'Third Punish',
  'Wug Strike',
  "God's Hammer",
  'Overslash',
  "Heaven's Drive",
  'Lightning Land',
  'Floral Flare Road',
  "Rich's Coin",
  'Stratum Tremor',
  'Petitio',
  'Gale Storm',
  'Acidified Zone Fire',
  'Acidified Zone Water',
  'Acidified Zone Wind',
  'Acidified Zone Earth',
  'Servant Weapon',
  'From the Abyss',
  'Axe Stomp',
  'Impact Crater',
  'Hesperus Lit',
  'The Vigilante at Night',
  'Only One Bullet',
  'Spiral Shooting',
  'Magazine for One',
  'Wild Fire',
  'Basic Grenade',
  'Hasty Fire in the Hole',
  'Grenade Dropping',
  'Mission Bombard',
  'Wild Shot',
  'Midnight Fallen',
] as const;

const dup = [];
for (const s of activePassiveSkillName) {
  if (OFFENSIVE_SKILL_NAMES.includes(s as any)) {
    dup.push(s);
  }
}

if (dup.length > 0) console.log('skillname_dupplicates', dup);

export type SKILL_NAME = (typeof activePassiveSkillName)[number] | (typeof OFFENSIVE_SKILL_NAMES)[number];
