import { DropdownModel } from './dropdown.model';

export interface ItemListModel {
  weaponList: DropdownModel[];
  leftWeaponList: DropdownModel[];
  weaponCardList: DropdownModel[];
  weaponEnchant1List: DropdownModel[];
  weaponEnchant2List: DropdownModel[];
  weaponEnchant3List: DropdownModel[];
  ammoList: DropdownModel[];
  headUpperList: DropdownModel[];
  headUpperEnchant1List: DropdownModel[];
  headUpperEnchant2List: DropdownModel[];
  headUpperEnchant3List: DropdownModel[];
  headMiddleList: DropdownModel[];
  headMiddleEnchant1List: DropdownModel[];
  headMiddleEnchant2List: DropdownModel[];
  headMiddleEnchant3List: DropdownModel[];
  headLowerList: DropdownModel[];
  headLowerEnchant1List: DropdownModel[];
  headLowerEnchant2List: DropdownModel[];
  headLowerEnchant3List: DropdownModel[];
  headCardList: DropdownModel[];
  armorList: DropdownModel[];
  armorCardList: DropdownModel[];
  armorEnchant1List: DropdownModel[];
  armorEnchant2List: DropdownModel[];
  armorEnchant3List: DropdownModel[];
  shieldList: DropdownModel[];
  shieldCardList: DropdownModel[];
  shieldEnchant1List: DropdownModel[];
  shieldEnchant2List: DropdownModel[];
  shieldEnchant3List: DropdownModel[];
  garmentList: DropdownModel[];
  garmentCardList: DropdownModel[];
  garmentEnchant1List: DropdownModel[];
  garmentEnchant2List: DropdownModel[];
  garmentEnchant3List: DropdownModel[];
  bootList: DropdownModel[];
  bootCardList: DropdownModel[];
  bootEnchant1List: DropdownModel[];
  bootEnchant2List: DropdownModel[];
  bootEnchant3List: DropdownModel[];
  accList: DropdownModel[];
  accCardList: DropdownModel[];
  accLeftList: DropdownModel[];
  accLeftCardList: DropdownModel[];
  accLeftEnchant1List: DropdownModel[];
  accLeftEnchant2List: DropdownModel[];
  accLeftEnchant3List: DropdownModel[];
  accRightList: DropdownModel[];
  accRightCardList: DropdownModel[];
  accRightEnchant1List: DropdownModel[];
  accRightEnchant2List: DropdownModel[];
  accRightEnchant3List: DropdownModel[];
  petList: DropdownModel[];

  costumeUpperList: DropdownModel[];

  costumeEnhUpperList: DropdownModel[];
  costumeEnhMiddleList: DropdownModel[];
  costumeEnhLowerList: DropdownModel[];
  costumeEnhGarmentList: DropdownModel[];
  costumeEnhGarment4List: DropdownModel[];

  shadowWeaponList: DropdownModel[];
  shadowArmorList: DropdownModel[];
  shadowShieldList: DropdownModel[];
  shadowBootList: DropdownModel[];
  shadowEarringList: DropdownModel[];
  shadowPendantList: DropdownModel[];
}
