import { Acute, Adamatine, AttackDelay, EA, ExpertFighter, ExpertMagician, MagicEess, MasterArc, Mettle, Spell, Tenacity } from "./_basic";

export const bp7_4 = [
  ExpertFighter._3,
  ExpertFighter._5,
  EA._3,
  EA._5,
  ExpertMagician._3,
  ExpertMagician._5,
  Spell._3,
  Spell._5,
  AttackDelay._2,
  AttackDelay._4,
];

export const bp7_2 = [
  Acute._2,
  Acute._3,
  Acute._4,
  Acute._5,
  Acute._6,
  Acute._7,
  Acute._8,
  Acute._9,
  Acute._10,

  Tenacity._2,
  Tenacity._3,
  Tenacity._4,
  Tenacity._5,
  Tenacity._6,
  Tenacity._7,
  Tenacity._8,
  Tenacity._9,
  Tenacity._10,

  MasterArc._2,
  MasterArc._3,
  MasterArc._4,
  MasterArc._5,
  MasterArc._6,
  MasterArc._7,
  MasterArc._8,
  MasterArc._9,
  MasterArc._10,

  Mettle._2,
  Mettle._3,
  Mettle._4,
  Mettle._5,
  Mettle._6,
  Mettle._7,
  Mettle._8,
  Mettle._9,
  Mettle._10,

  MagicEess._2,
  MagicEess._3,
  MagicEess._4,
  MagicEess._5,
  MagicEess._6,
  MagicEess._7,
  MagicEess._8,
  MagicEess._9,
  MagicEess._10,

  Adamatine._2,
  Adamatine._3,
  Adamatine._4,
  Adamatine._5,
  Adamatine._6,
  Adamatine._7,
  Adamatine._8,
  Adamatine._9,
  Adamatine._10,

];