import { fs45, sp34, ea34, sh34, hitPlus34 } from "./_basic";

export const stellar = [
  'Star_Of_Mettle1',
  'Star_Of_Mettle2',
  'Star_Of_Mettle3',
  'Star_Of_Mettle4',
  'Star_Of_Mettle5',
  'Star_Of_MasterArcher1',
  'Star_Of_MasterArcher2',
  'Star_Of_MasterArcher3',
  'Star_Of_MasterArcher4',
  'Star_Of_MasterArcher5',
  'Star_Of_Sharp1',
  'Star_Of_Sharp2',
  'Star_Of_Sharp3',
  'Star_Of_Sharp4',
  'Star_Of_Sharp5',
  'Star_Of_Spell1',
  'Star_Of_Spell2',
  'Star_Of_Spell3',
  'Star_Of_Spell4',
  'Star_Of_Spell5',
  'Star_Of_Speed1',
  'Star_Of_Speed2',
  'Star_Of_Speed3',
  'Star_Of_Speed4',
  'Star_Of_Speed5',
  'Star_Of_Vital1',
  'Star_Of_Vital2',
  'Star_Of_Vital3',
  'Star_Of_Vital4',
  'Star_Of_Vital5',
  // 'Star_Of_Spirit1', non damage
  // 'Star_Of_Spirit2',
  // 'Star_Of_Spirit3',
  // 'Star_Of_Spirit4',
  // 'Star_Of_Spirit5',
];
export const stellarAcc4 = [...fs45, ...sp34, ...ea34, ...sh34, ...stellar];
export const stellarAcc3 = [...stellarAcc4];
export const stellarAcc2 = [
  'Star_Cluster_Of_Str1',
  'Star_Cluster_Of_Str2',
  'Star_Cluster_Of_Str3',
  'Star_Cluster_Of_Str4',
  'Star_Cluster_Of_Str5',
  'Star_Cluster_Of_Luk1',
  'Star_Cluster_Of_Luk2',
  'Star_Cluster_Of_Luk3',
  'Star_Cluster_Of_Luk4',
  'Star_Cluster_Of_Luk5',
  'Star_Cluster_Of_Int1',
  'Star_Cluster_Of_Int2',
  'Star_Cluster_Of_Int3',
  'Star_Cluster_Of_Int4',
  'Star_Cluster_Of_Int5',
  'Star_Cluster_Of_Res1',
  'Star_Cluster_Of_Res2',
  'Star_Cluster_Of_Res3',
  'Star_Cluster_Of_Res4',
  'Star_Cluster_Of_Res5',
];

export const signetAcc4 = ['Token_Of_Life'];
export const signetAcc3 = [
  ...sp34,
  ...ea34,
  ...sh34,
  ...hitPlus34,
  'Signet_Of_Pow1',
  'Signet_Of_Pow2',
  'Signet_Of_Pow3',
  'Signet_Of_Pow4',
  'Signet_Of_Pow5',
  'Signet_Of_Con1',
  'Signet_Of_Con2',
  'Signet_Of_Con3',
  'Signet_Of_Con4',
  'Signet_Of_Con5',
  'Signet_Of_Spl1',
  'Signet_Of_Spl2',
  'Signet_Of_Spl3',
  'Signet_Of_Spl4',
  'Signet_Of_Spl5',
  'Signet_Of_Sta1',
  'Signet_Of_Sta2',
  'Signet_Of_Sta3',
  'Signet_Of_Sta4',
  'Signet_Of_Sta5',
  'Signet_Of_Crt1',
  'Signet_Of_Crt2',
  'Signet_Of_Crt3',
  'Signet_Of_Crt4',
  'Signet_Of_Crt5',
  // 'Signet_Of_Wis1', non damage
  // 'Signet_Of_Wis2',
  // 'Signet_Of_Wis3',
  // 'Signet_Of_Wis4',
  // 'Signet_Of_Wis5',
];

export const manSpringGarment4 = [
  "Physical_Seed_1",
  "Physical_Seed_2",
  "Physical_Seed_3",
  "Physical_Seed_4",
  "Physical_Seed_5",
  "Physical_Seed_6",
  "Physical_Seed_7",
  "Physical_Seed_8",
  "Physical_Seed_9",
  "Physical_Seed_10",
  'Physical_Leaf_1',
  'Physical_Leaf_2',
  'Physical_Leaf_3',
  'Physical_Leaf_4',
  'Physical_Leaf_5',
]
export const cirSpringGarment4 = [
  ...manSpringGarment4,
  'Physical_Flower_1',
  'Physical_Flower_2',
  'Physical_Flower_3',
  'Physical_Flower_4',
  'Physical_Flower_5',
]
export const manSpringGarment3 = [
  "Physical_Fruit_1",
  "Physical_Fruit_2",
  "Physical_Fruit_3",
  "Physical_Fruit_4",
  "Physical_Fruit_5",
  "Physical_Fruit_6",
  "Physical_Fruit_7",
  "Physical_Fruit_8",
  "Physical_Fruit_9",
  "Physical_Fruit_10",
  "Physical_Fruit_11",
  "Physical_Fruit_12",
  "Physical_Fruit_13",
  "Physical_Fruit_14",
  "Physical_Fruit_15",
]
export const cirSpringGarment3 = [
  ...manSpringGarment3,
  "Physical_Fruit_16",
  "Physical_Fruit_17",
  "Physical_Fruit_18",
  "Physical_Fruit_19",
  "Physical_Fruit_20",
]
export const manSpringGarment2 = [
  "Life_of_Spring_1",
  "Life_of_Spring_2",
  "Life_of_Spring_3",
  "Life_of_Spring_4",
  "Life_of_Spring_5",
  "Life_of_Spring_6",
  "Life_of_Spring_7",
  "Life_of_Spring_8",
  "Life_of_Spring_9",
  "Life_of_Spring_10",
  "Life_of_Spring_11",
  "Life_of_Spring_12",
  "Life_of_Spring_13",
  "Life_of_Spring_14",
  "Life_of_Spring_15",
]
export const cirSpringGarment2 = [
  'Life_of_Spring_Pow',
  'Life_of_Spring_Sta',
  'Life_of_Spring_Crt',
  ...manSpringGarment2,
  "Life_of_Spring_16",
  "Life_of_Spring_17",
  "Life_of_Spring_18",
  "Life_of_Spring_19",
  "Life_of_Spring_20",
]

export const manAutumnSummer2 = [

  "Life_of_Summer_1",
  "Life_of_Summer_2",
  "Life_of_Summer_3",
  "Life_of_Summer_4",
  "Life_of_Summer_5",
  "Life_of_Summer_6",
  "Life_of_Summer_7",
  "Life_of_Summer_8",
  "Life_of_Summer_9",
  "Life_of_Summer_10",
  "Life_of_Summer_11",
  "Life_of_Summer_12",
  "Life_of_Summer_13",
  "Life_of_Summer_14",
  "Life_of_Summer_15",
]
export const cirAutumnSummer2 = [
  'Life_of_Summer_Con',
  'Life_of_Summer_Sta',
  'Life_of_Summer_Crt',
  ...manAutumnSummer2,
  "Life_of_Summer_16",
  "Life_of_Summer_17",
  "Life_of_Summer_18",
  "Life_of_Summer_19",
  "Life_of_Summer_20",
]

export const manAutumnWinter2 = [
  "Life_of_Winter_1",
  "Life_of_Winter_2",
  "Life_of_Winter_3",
  "Life_of_Winter_4",
  "Life_of_Winter_5",
  "Life_of_Winter_6",
  "Life_of_Winter_7",
  "Life_of_Winter_8",
  "Life_of_Winter_9",
  "Life_of_Winter_10",
  "Life_of_Winter_11",
  "Life_of_Winter_12",
  "Life_of_Winter_13",
  "Life_of_Winter_14",
  "Life_of_Winter_15",
]
export const cirAutumnWinter2 = [
  'Life_of_Winter_Pow',
  'Life_of_Winter_Con',
  'Life_of_Winter_Crt',
  ...manAutumnWinter2,
  "Life_of_Winter_16",
  "Life_of_Winter_17",
  "Life_of_Winter_18",
  "Life_of_Winter_19",
  "Life_of_Winter_20",
]

export const manAutumnGarment4 = [
  'Magical_Seed_1',
  'Magical_Seed_2',
  'Magical_Seed_3',
  'Magical_Seed_4',
  'Magical_Seed_5',
  'Magical_Seed_6',
  'Magical_Seed_7',
  'Magical_Seed_8',
  'Magical_Seed_9',
  'Magical_Seed_10',
  'Magical_Leaf_1',
  'Magical_Leaf_2',
  'Magical_Leaf_3',
  'Magical_Leaf_4',
  'Magical_Leaf_5',
]
export const cirAutumnGarment4 = [
  ...manAutumnGarment4,
  'Magical_Flower_1',
  'Magical_Flower_2',
  'Magical_Flower_3',
  'Magical_Flower_4',
  'Magical_Flower_5',
]
export const manAutumnGarment3 = [
  'Magical_Fruit_1',
  'Magical_Fruit_2',
  'Magical_Fruit_3',
  'Magical_Fruit_4',
  'Magical_Fruit_5',
  'Magical_Fruit_6',
  'Magical_Fruit_7',
  'Magical_Fruit_8',
  'Magical_Fruit_9',
  'Magical_Fruit_10',
  'Magical_Fruit_11',
  'Magical_Fruit_12',
  'Magical_Fruit_13',
  'Magical_Fruit_14',
  'Magical_Fruit_15',
]
export const cirAutumnGarment3 = [
  ...manAutumnGarment3,
  'Magical_Fruit_16',
  'Magical_Fruit_17',
  'Magical_Fruit_18',
  'Magical_Fruit_19',
  'Magical_Fruit_20',
]
export const manAutumnGarment2 = [
  "Life_of_Autumn_1",
  "Life_of_Autumn_2",
  "Life_of_Autumn_3",
  "Life_of_Autumn_4",
  "Life_of_Autumn_5",
  "Life_of_Autumn_6",
  "Life_of_Autumn_7",
  "Life_of_Autumn_8",
  "Life_of_Autumn_9",
  "Life_of_Autumn_10",
  "Life_of_Autumn_11",
  "Life_of_Autumn_12",
  "Life_of_Autumn_13",
  "Life_of_Autumn_14",
  "Life_of_Autumn_15",
]
export const cirAutumnGarment2 = [
  'Life_of_Autumn_Spl',
  'Life_of_Autumn_Sta',
  'Life_of_Autumn_Wis',
  ...manAutumnGarment2,
  "Life_of_Autumn_16",
  "Life_of_Autumn_17",
  "Life_of_Autumn_18",
  "Life_of_Autumn_19",
  "Life_of_Autumn_20",
]