export const dimWeapon3 = [
  'Glacier_F_Orb_81',
  'Glacier_F_Orb_82',
  'Glacier_F_Orb_83',
  'Glacier_F_Orb_84',
  'Glacier_F_Orb_85',
  'Glacier_F_Orb_86',
  'Glacier_F_Orb_87',
  'Glacier_F_Orb_88',
  'Glacier_F_Orb_89',
  'Glacier_F_Orb_90',
  'Glacier_F_Orb_91',
  'Glacier_F_Orb_92',
  'Glacier_F_Orb_93',
  'Glacier_F_Orb_94',
  'Glacier_F_Orb_95',
  'Glacier_F_Orb_96',
  'Glacier_F_Orb_97',
  'Glacier_F_Orb_98',
  'Glacier_F_Orb_99',
  'Glacier_F_Orb_100',
  'Glacier_F_Orb_101',
  'Glacier_F_Orb_102',
  'Glacier_F_Orb_103',
  'Glacier_F_Orb_104',
  'Glacier_F_Orb_105',
  'Glacier_F_Orb_106',
  'Glacier_F_Orb_107',
  'Glacier_F_Orb_108',
  'Glacier_F_Orb_109',
  'Glacier_F_Orb_110',
  'Glacier_F_Orb_111',
  'Glacier_F_Orb_112',
  'Glacier_F_Orb_113',
  'Glacier_F_Orb_114',
  'Glacier_F_Orb_115',
  'Glacier_F_Orb_116',
  'Glacier_F_Orb_117',
  'Glacier_F_Orb_118',
  'Glacier_F_Orb_119',
  'Glacier_F_Orb_120',
  'Glacier_F_Orb_121',
  'Glacier_F_Orb_122',
  'Glacier_F_Orb_123',
  'Glacier_F_Orb_124',
  'Glacier_F_Orb_125',
  'Glacier_F_Orb_126',
  'Glacier_F_Orb_127',
  'Glacier_F_Orb_128',
  'Glacier_F_Orb_129',
  'Glacier_F_Orb_130',
  'Glacier_F_Orb_131',
  'Glacier_F_Orb_132',
  'Glacier_F_Orb_133',
  'Glacier_F_Orb_134',
  'Glacier_F_Orb_135',
  'Glacier_F_Orb_136',
  'Glacier_F_Orb_137',
  'Glacier_F_Orb_138',
  'Glacier_F_Orb_139',
  'Glacier_F_Orb_140',
  'Glacier_F_Orb_141',
  'Glacier_F_Orb_142',
  'Glacier_F_Orb_143',
  'Glacier_F_Orb_144',
  'Glacier_F_Orb_145',
  'Glacier_F_Orb_146',
  'Glacier_F_Orb_147',
  'Glacier_F_Orb_148',
  'Glacier_F_Orb_149',
  'Glacier_F_Orb_162',
  'Glacier_F_Orb_163',
  'Glacier_F_Orb_164',
  'Glacier_F_Orb_165',
  'Glacier_F_Orb_166',
  'Glacier_F_Orb_167',
]

export const dimWeapon4 = [
  'Glacier_F_Orb_1',
  'Glacier_F_Orb_2',
  'Glacier_F_Orb_3',
  'Glacier_F_Orb_4',
  'Glacier_F_Orb_5',
  'Glacier_F_Orb_6',
  'Glacier_F_Orb_7',
  'Glacier_F_Orb_8',
  'Glacier_F_Orb_9',
  'Glacier_F_Orb_10',
  'Glacier_F_Orb_11',
  'Glacier_F_Orb_12',
  'Glacier_F_Orb_13',
  'Glacier_F_Orb_14',
  'Glacier_F_Orb_15',
  'Glacier_F_Orb_16',
  'Glacier_F_Orb_17',
  'Glacier_F_Orb_18',
  'Glacier_F_Orb_19',
  'Glacier_F_Orb_20',
  'Glacier_F_Orb_21',
  'Glacier_F_Orb_22',
  'Glacier_F_Orb_23',
  'Glacier_F_Orb_24',
  'Glacier_F_Orb_25',
  'Glacier_F_Orb_26',
  'Glacier_F_Orb_27',
  'Glacier_F_Orb_28',
  'Glacier_F_Orb_29',
  'Glacier_F_Orb_30',
  'Glacier_F_Orb_31',
  'Glacier_F_Orb_32',
  'Glacier_F_Orb_33',
  'Glacier_F_Orb_34',
  'Glacier_F_Orb_35',
  'Glacier_F_Orb_36',
  'Glacier_F_Orb_37',
  'Glacier_F_Orb_38',
  'Glacier_F_Orb_39',
  'Glacier_F_Orb_40',
  'Glacier_F_Orb_41',
  'Glacier_F_Orb_42',
  'Glacier_F_Orb_43',
  'Glacier_F_Orb_44',
  'Glacier_F_Orb_45',
  'Glacier_F_Orb_46',
  'Glacier_F_Orb_47',
  'Glacier_F_Orb_48',
  'Glacier_F_Orb_49',
  'Glacier_F_Orb_50',
  'Glacier_F_Orb_51',
  'Glacier_F_Orb_52',
  'Glacier_F_Orb_53',
  'Glacier_F_Orb_54',
  'Glacier_F_Orb_55',
  'Glacier_F_Orb_56',
  'Glacier_F_Orb_57',
  'Glacier_F_Orb_58',
  'Glacier_F_Orb_59',
  'Glacier_F_Orb_60',
  'Glacier_F_Orb_61',
  'Glacier_F_Orb_62',
  'Glacier_F_Orb_63',
  'Glacier_F_Orb_64',
  'Glacier_F_Orb_65',
  'Glacier_F_Orb_66',
  'Glacier_F_Orb_67',
  'Glacier_F_Orb_68',
  'Glacier_F_Orb_69',
  'Glacier_F_Orb_70',
  'Glacier_F_Orb_71',
  'Glacier_F_Orb_72',
  'Glacier_F_Orb_73',
  'Glacier_F_Orb_74',
  'Glacier_F_Orb_75',
  'Glacier_F_Orb_76',
  'Glacier_F_Orb_77',
  'Glacier_F_Orb_78',
  'Glacier_F_Orb_79',
  'Glacier_F_Orb_80',
  ...dimWeapon3,
]

export const dimWeapon2 = [
  'Physical_Grade_1',
  'Physical_Grade_2',
  'Physical_Grade_3',
  'Physical_Grade_4',
  'Physical_Grade_5',
  'Magical_Grade_1',
  'Magical_Grade_2',
  'Magical_Grade_3',
  'Magical_Grade_4',
  'Magical_Grade_5',
]

export const dimGlaArmor4 = [
  // 'Snake_A_Def_1',
  // 'Snake_A_Def_2',
  // 'Snake_A_Def_3',
  'Snake_A_Def_4',
  'Snake_A_Def_5',
  'Snake_A_Def_6',
  'Snake_A_Def_7',
  'Snake_A_Def_8',
  'Snake_A_Def_9',
  'Snake_A_Def_10',
]
export const dimGlaArmor3 = [
  // 'Snake_A_Atk_1',
  // 'Snake_A_Atk_2',
  // 'Snake_A_Atk_3',
  'Snake_A_Atk_4',
  'Snake_A_Atk_5',
  'Snake_A_Atk_6',
  'Snake_A_Atk_7',
  'Snake_A_Atk_8',
  'Snake_A_Atk_9',
  'Snake_A_Atk_10',
  // 'Snake_A_Matk_1',
  // 'Snake_A_Matk_2',
  // 'Snake_A_Matk_3',
  'Snake_A_Matk_4',
  'Snake_A_Matk_5',
  'Snake_A_Matk_6',
  'Snake_A_Matk_7',
  'Snake_A_Matk_8',
  'Snake_A_Matk_9',
  'Snake_A_Matk_10',
]
export const dimGlaArmor2 = [
  'Snake_G_Blessing',
]

export const dimGlaGarment4 = [
  // 'Snake_H_Def_1',
  // 'Snake_H_Def_2',
  // 'Snake_H_Def_3',
  'Snake_H_Def_4',
  'Snake_H_Def_5',
  'Snake_H_Def_6',
  'Snake_H_Def_7',
  'Snake_H_Def_8',
  'Snake_H_Def_9',
  'Snake_H_Def_10',
]
export const dimGlaGarment3 = [
  // 'Snake_H_Atk_1',
  // 'Snake_H_Atk_2',
  // 'Snake_H_Atk_3',
  'Snake_H_Atk_4',
  'Snake_H_Atk_5',
  'Snake_H_Atk_6',
  'Snake_H_Atk_7',
  'Snake_H_Atk_8',
  'Snake_H_Atk_9',
  'Snake_H_Atk_10',
  // 'Snake_H_Matk_1',
  // 'Snake_H_Matk_2',
  // 'Snake_H_Matk_3',
  'Snake_H_Matk_4',
  'Snake_H_Matk_5',
  'Snake_H_Matk_6',
  'Snake_H_Matk_7',
  'Snake_H_Matk_8',
  'Snake_H_Matk_9',
  'Snake_H_Matk_10',
]
export const dimGlaGarment2 = [
  'Snake_G_Grace',
]

export const dimGlaBoot4 = [
  // 'Snake_S_Def_1',
  // 'Snake_S_Def_2',
  // 'Snake_S_Def_3',
  'Snake_S_Def_4',
  'Snake_S_Def_5',
  'Snake_S_Def_6',
  'Snake_S_Def_7',
  'Snake_S_Def_8',
  'Snake_S_Def_9',
  'Snake_S_Def_10',
]
export const dimGlaBoot3 = [
  // 'Snake_S_Atk_1',
  // 'Snake_S_Atk_2',
  // 'Snake_S_Atk_3',
  'Snake_S_Atk_4',
  'Snake_S_Atk_5',
  'Snake_S_Atk_6',
  'Snake_S_Atk_7',
  'Snake_S_Atk_8',
  'Snake_S_Atk_9',
  'Snake_S_Atk_10',
  // 'Snake_S_Matk_1',
  // 'Snake_S_Matk_2',
  // 'Snake_S_Matk_3',
  'Snake_S_Matk_4',
  'Snake_S_Matk_5',
  'Snake_S_Matk_6',
  'Snake_S_Matk_7',
  'Snake_S_Matk_8',
  'Snake_S_Matk_9',
  'Snake_S_Matk_10',
]
export const dimGlaBoot2 = [
  'Snake_G_Glory',
]
