import { int, luk, str, vit } from "./_basic"

export const dimensionHead4 = [
  ...str(1, 5),
  ...int(1, 5),
  ...vit(1, 5),
  ...luk(1, 5),
]
export const dimensionHead3 = [
  "T_D_Jewel_STR_1",
  "T_D_Jewel_STR_2",
  "T_D_Jewel_STR_3",
  "T_D_Jewel_AGI_1",
  "T_D_Jewel_AGI_2",
  "T_D_Jewel_AGI_3",
  "T_D_Jewel_DEX_1",
  "T_D_Jewel_DEX_2",
  "T_D_Jewel_DEX_3",
  "T_D_Jewel_VIT_1",
  "T_D_Jewel_VIT_2",
  "T_D_Jewel_VIT_3",
  "T_D_Jewel_INT_1",
  "T_D_Jewel_INT_2",
  "T_D_Jewel_INT_3",
  "T_D_Jewel_LUK_1",
  "T_D_Jewel_LUK_2",
  "T_D_Jewel_LUK_3",
  "T_D_Jewel_SPR_1",
  "T_D_Jewel_SPR_2",
  "T_D_Jewel_SPR_3",
  "T_D_Jewel_WIS_1",
  "T_D_Jewel_WIS_2",
  "T_D_Jewel_WIS_3",
]
export const dimensionHead2 = [
  'Acute_Jewel_3',
  'Acute_Jewel_4',
  'Acute_Jewel_5',
  'Acute_Jewel_6',
  'Acute_Jewel_7',
  'Acute_Jewel_8',
  'Acute_Jewel_9',
  'Acute_Jewel_10',
  'Tenacity_Jewel_3',
  'Tenacity_Jewel_4',
  'Tenacity_Jewel_5',
  'Tenacity_Jewel_6',
  'Tenacity_Jewel_7',
  'Tenacity_Jewel_8',
  'Tenacity_Jewel_9',
  'Tenacity_Jewel_10',
  'Master_A_Jewel_3',
  'Master_A_Jewel_4',
  'Master_A_Jewel_5',
  'Master_A_Jewel_6',
  'Master_A_Jewel_7',
  'Master_A_Jewel_8',
  'Master_A_Jewel_9',
  'Master_A_Jewel_10',
  'Mettle_Jewel_3',
  'Mettle_Jewel_4',
  'Mettle_Jewel_5',
  'Mettle_Jewel_6',
  'Mettle_Jewel_7',
  'Mettle_Jewel_8',
  'Mettle_Jewel_9',
  'Mettle_Jewel_10',
  'Magic_E_Jewel_3',
  'Magic_E_Jewel_4',
  'Magic_E_Jewel_5',
  'Magic_E_Jewel_6',
  'Magic_E_Jewel_7',
  'Magic_E_Jewel_8',
  'Magic_E_Jewel_9',
  'Magic_E_Jewel_10',
  'Spell_Jewel_3',
  'Spell_Jewel_4',
  'Spell_Jewel_5',
  'Spell_Jewel_6',
  'Spell_Jewel_7',
  'Spell_Jewel_8',
  'Spell_Jewel_9',
  'Spell_Jewel_10',
  'Adamatine_Jewel_3',
  'Adamatine_Jewel_4',
  'Adamatine_Jewel_5',
  'Adamatine_Jewel_6',
  'Adamatine_Jewel_7',
  'Adamatine_Jewel_8',
  'Adamatine_Jewel_9',
  'Adamatine_Jewel_10',
]

export const dimensionWeapon3 = [
  "Barmund_Flame3",
  "Barmund_Ice3",
  "Barmund_Plain3",
  "Barmund_Death3",
  'Barmund_Poison3',
]
export const dimensionWeapon4 = [
  "Bio_Jam_Df2",
  "Bio_Jam_Es2",
  "Bio_Jam_Vl2",
  "Bio_Jam_Eq2",
  "Bio_Jam_Hd2",
]