
export const issgardCrown4 = [
  'Isgard_4',
]
export const issgardCrown3 = [
  'Isgard_3_Warrior',
  'Isgard_3_Ranger',
  'Isgard_3_Assassin',
  'Isgard_3_Mage',
]
export const issgardCrown2 = [
  'Isgard_2_Warrior2',
  'Isgard_2_Ranger2',
  'Isgard_2_Assassin2',
  'Isgard_2_Mage2',
]

export const glacierGuard4 = [
  'Ice_C_Orb_D',
  'Ice_C_Orb_A',
]
export const glacierGuard3 = [
  'Ice_C_Orb_Res',
  'Ice_C_Orb_Mres',
]
export const glacierGuard2 = [
  'Ice_C_Orb_Guard',
  'Ice_C_Orb_Intel',
]

export const glacierArmor4 = [
  'Ice_C_Orb_Pow_S',
  'Ice_C_Orb_Spl_W',
  'Ice_C_Orb_Con_C',
  'Ice_C_Orb_S_Delay',
]
export const glacierArmor3 = [
  'Ice_C_Orb_War',
  'Ice_C_Orb_Ran',
  'Ice_C_Orb_Mag',
  'Ice_C_Orb_Force',
]
export const glacierArmor2 = [
  'Ice_C_Orb_War2',
  'Ice_C_Orb_Ran2',
  'Ice_C_Orb_Mag2',
]

export const glacierGarment4 = [
  'Ice_C_Orb_Def',
  'Ice_C_Orb_Mdef',
]
export const glacierGarment3 = [
  'Ice_C_Orb_Speed',
  'Ice_C_Orb_Caster',
  'Ice_C_Orb_Guide',
]
export const glacierGarment2 = [
  // 'Ice_C_Orb_Above',
  'Ice_C_Orb_P_Full',
]

export const glacierBoot4 = [
  'Ice_C_Orb_Hp',
  'Ice_C_Orb_Sp',
  'Ice_C_Orb_F_Cast',
]
export const glacierBoot3 = [
  'Ice_C_Orb_P_F',
  'Ice_C_Orb_M_F',
  'Ice_C_Orb_Robust',
]
export const glacierBoot2 = [
  'Ice_C_Orb_Ov_Pow',
  'Ice_C_Orb_Fi_Con',
  'Ice_C_Orb_Bu_Spl',
]

export const glacierAccR4 = [
  'Ice_C_Orb_Str',
  'Ice_C_Orb_Dex',
  'Ice_C_Orb_Int',
  'Ice_C_Orb_Spd',
]
export const glacierAccL4 = [
  'Ice_C_Orb_Agi',
  'Ice_C_Orb_Vit',
  'Ice_C_Orb_Luk',
  'Ice_C_Orb_Spd',
]
export const glacierAcc3 = [
  'Ice_C_Orb_F_Spirit',
  'Ice_C_Orb_E_Archer',
  'Ice_C_Orb_Fatal',
  'Ice_C_Orb_Spell',
]
export const glacierAcc2 = [
  'Ice_C_Orb_P_P',
  'Ice_C_Orb_M_P',
  'Ice_C_Orb_A_Force',
]

export const glacierWea4 = [
  'Glacier_F_Orb_150',
  'Glacier_F_Orb_151',
  'Glacier_F_Orb_152',
]
export const glacierWea3 = [
  'Glacier_F_Orb_153',
  'Glacier_F_Orb_154',
  'Glacier_F_Orb_155',
  'Glacier_F_Orb_156',
  'Glacier_F_Orb_157',
  'Glacier_F_Orb_158',
  'Glacier_F_Orb_159',
  'Glacier_F_Orb_160',
  'Glacier_F_Orb_161',
]
export const glacierWea2 = [
  'Glacier_F_Orb_156',
  'Glacier_F_Orb_157',
  'Glacier_F_Orb_158',
  'Glacier_F_Orb_159',
  'Glacier_F_Orb_160',
  'Glacier_F_Orb_161',
  'Glacier_F_Orb_1',
  'Glacier_F_Orb_2',
  'Glacier_F_Orb_3',
  'Glacier_F_Orb_4',
  'Glacier_F_Orb_5',
  'Glacier_F_Orb_6',
  'Glacier_F_Orb_7',
  'Glacier_F_Orb_8',
  'Glacier_F_Orb_9',
  'Glacier_F_Orb_10',
  'Glacier_F_Orb_11',
  'Glacier_F_Orb_12',
  'Glacier_F_Orb_13',
  'Glacier_F_Orb_14',
  'Glacier_F_Orb_15',
  'Glacier_F_Orb_16',
  'Glacier_F_Orb_17',
  'Glacier_F_Orb_18',
  'Glacier_F_Orb_19',
  'Glacier_F_Orb_20',
  'Glacier_F_Orb_21',
  'Glacier_F_Orb_22',
  'Glacier_F_Orb_23',
  'Glacier_F_Orb_24',
  'Glacier_F_Orb_25',
  'Glacier_F_Orb_26',
  'Glacier_F_Orb_27',
  'Glacier_F_Orb_28',
  'Glacier_F_Orb_29',
  'Glacier_F_Orb_30',
  'Glacier_F_Orb_31',
  'Glacier_F_Orb_32',
  'Glacier_F_Orb_33',
  'Glacier_F_Orb_34',
  'Glacier_F_Orb_35',
  'Glacier_F_Orb_36',
  'Glacier_F_Orb_37',
  'Glacier_F_Orb_38',
  'Glacier_F_Orb_39',
  'Glacier_F_Orb_40',
  'Glacier_F_Orb_41',
  'Glacier_F_Orb_42',
  'Glacier_F_Orb_43',
  'Glacier_F_Orb_44',
  'Glacier_F_Orb_45',
  'Glacier_F_Orb_46',
  'Glacier_F_Orb_47',
  'Glacier_F_Orb_48',
  'Glacier_F_Orb_49',
  'Glacier_F_Orb_50',
  'Glacier_F_Orb_51',
  'Glacier_F_Orb_52',
  'Glacier_F_Orb_53',
  'Glacier_F_Orb_54',
  'Glacier_F_Orb_55',
  'Glacier_F_Orb_56',
  'Glacier_F_Orb_57',
  'Glacier_F_Orb_58',
  'Glacier_F_Orb_59',
  'Glacier_F_Orb_60',
  'Glacier_F_Orb_61',
  'Glacier_F_Orb_62',
  'Glacier_F_Orb_63',
  'Glacier_F_Orb_64',
  'Glacier_F_Orb_65',
  'Glacier_F_Orb_66',
  'Glacier_F_Orb_67',
  'Glacier_F_Orb_68',
  'Glacier_F_Orb_69',
  'Glacier_F_Orb_70',
  'Glacier_F_Orb_71',
  'Glacier_F_Orb_72',
  'Glacier_F_Orb_73',
  'Glacier_F_Orb_74',
  'Glacier_F_Orb_75',
  'Glacier_F_Orb_76',
  'Glacier_F_Orb_77',
  'Glacier_F_Orb_78',
  'Glacier_F_Orb_79',
  'Glacier_F_Orb_80',
]
export const glacierWea1 = [
  'Glacier_F_Orb_156',
  'Glacier_F_Orb_157',
  'Glacier_F_Orb_158',
  'Glacier_F_Orb_159',
  'Glacier_F_Orb_160',
  'Glacier_F_Orb_161',
  'Glacier_F_Orb_81',
  'Glacier_F_Orb_82',
  'Glacier_F_Orb_83',
  'Glacier_F_Orb_84',
  'Glacier_F_Orb_85',
  'Glacier_F_Orb_86',
  'Glacier_F_Orb_87',
  'Glacier_F_Orb_88',
  'Glacier_F_Orb_89',
  'Glacier_F_Orb_90',
  'Glacier_F_Orb_91',
  'Glacier_F_Orb_92',
  'Glacier_F_Orb_93',
  'Glacier_F_Orb_94',
  'Glacier_F_Orb_95',
  'Glacier_F_Orb_96',
  'Glacier_F_Orb_97',
  'Glacier_F_Orb_98',
  'Glacier_F_Orb_99',
  'Glacier_F_Orb_100',
  'Glacier_F_Orb_101',
  'Glacier_F_Orb_102',
  'Glacier_F_Orb_103',
  'Glacier_F_Orb_104',
  'Glacier_F_Orb_105',
  'Glacier_F_Orb_106',
  'Glacier_F_Orb_107',
  'Glacier_F_Orb_108',
  'Glacier_F_Orb_109',
  'Glacier_F_Orb_110',
  'Glacier_F_Orb_111',
  'Glacier_F_Orb_112',
  'Glacier_F_Orb_113',
  'Glacier_F_Orb_114',
  'Glacier_F_Orb_115',
  'Glacier_F_Orb_116',
  'Glacier_F_Orb_117',
  'Glacier_F_Orb_118',
  'Glacier_F_Orb_119',
  'Glacier_F_Orb_120',
  'Glacier_F_Orb_121',
  'Glacier_F_Orb_122',
  'Glacier_F_Orb_123',
  'Glacier_F_Orb_124',
  'Glacier_F_Orb_125',
  'Glacier_F_Orb_126',
  'Glacier_F_Orb_127',
  'Glacier_F_Orb_128',
  'Glacier_F_Orb_129',
  'Glacier_F_Orb_130',
  'Glacier_F_Orb_131',
  'Glacier_F_Orb_132',
  'Glacier_F_Orb_133',
  'Glacier_F_Orb_134',
  'Glacier_F_Orb_135',
  'Glacier_F_Orb_136',
  'Glacier_F_Orb_137',
  'Glacier_F_Orb_138',
  'Glacier_F_Orb_139',
  'Glacier_F_Orb_140',
  'Glacier_F_Orb_141',
  'Glacier_F_Orb_142',
  'Glacier_F_Orb_143',
  'Glacier_F_Orb_144',
  'Glacier_F_Orb_145',
  'Glacier_F_Orb_146',
  'Glacier_F_Orb_147',
  'Glacier_F_Orb_148',
  'Glacier_F_Orb_149',
  'Glacier_F_Orb_162',
  'Glacier_F_Orb_163',
  'Glacier_F_Orb_164',
  'Glacier_F_Orb_165',
  'Glacier_F_Orb_166',
  'Glacier_F_Orb_167',
]