import { EA, FS, Sharp, Spell } from "./_basic";

export const nebularPendant4 = [
  Spell._3,
  Spell._4,
  EA._3,
  EA._4,
  FS._3,
  FS._4,
  Sharp._3,
  Sharp._4,
  'Star_Of_Mettle1',
  'Star_Of_Mettle2',
  'Star_Of_MasterArcher1',
  'Star_Of_MasterArcher2',
  'Star_Of_Sharp1',
  'Star_Of_Sharp2',
  'Star_Of_Spell1',
  'Star_Of_Spell2',
  'Star_Of_Speed1',
  'Star_Of_Speed2',
  'Star_Of_Vital1',
  'Star_Of_Vital2',
];

export const nebularPendant3 = [
  'Star_Of_Mettle3',
  'Star_Of_Mettle4',
  'Star_Of_Mettle5',
  'Star_Of_MasterArcher3',
  'Star_Of_MasterArcher4',
  'Star_Of_MasterArcher5',
  'Star_Of_Sharp3',
  'Star_Of_Sharp4',
  'Star_Of_Sharp5',
  'Star_Of_Spell3',
  'Star_Of_Spell4',
  'Star_Of_Spell5',
  'Star_Of_Speed3',
  'Star_Of_Speed4',
  'Star_Of_Speed5',
  'Star_Of_Vital3',
  'Star_Of_Vital4',
  'Star_Of_Vital5',
];