import { Acute, Adamatine, AttackDelay, EA, ExpertFighter, ExpertMagician, MagicEess, MasterArc, Mettle, SkillDelay, Spell, Tenacity } from "./_basic";

export const vivatusHead4 = [
  // Acute._1,
  Acute._2,
  Acute._3,
  Acute._4,
  Acute._5,
  // Tenacity._1,
  Tenacity._2,
  Tenacity._3,
  Tenacity._4,
  Tenacity._5,
  // MasterArc._1,
  MasterArc._2,
  MasterArc._3,
  MasterArc._4,
  MasterArc._5,
  // Adamatine._1,
  Adamatine._2,
  Adamatine._3,
  Adamatine._4,
  Adamatine._5,
  // MagicEess._1,
  MagicEess._2,
  MagicEess._3,
  MagicEess._4,
  MagicEess._5,
  // Mettle._1,
  Mettle._2,
  Mettle._3,
  Mettle._4,
  Mettle._5,
];

export const vivatusHead3 = [
  EA._3,
  EA._5,
  ExpertFighter._3,
  ExpertFighter._5,
  ExpertMagician._3,
  ExpertMagician._5,
  Spell._3,
  Spell._5,
  AttackDelay._2,
  AttackDelay._4,
  SkillDelay._1,
  SkillDelay._3,
];