export type SKILL_NAME =
  | '16th Night'
  | 'Acid Bomb'
  | 'Acid Demonstration'
  | 'Adoramus'
  | 'Adrenaline Rush'
  | 'Advanced Book'
  | 'Advanced Katar Mastery'
  | 'Aimed Bolt'
  | 'Stage Manner'
  | 'Rhythm Shooting'
  | 'Rhapsody of Mineworker'
  | 'Fidus Animus'
  | 'Serenade of Jawaii'
  | '_Trouvere_Troubadour_ignore_res_mres'
  | '_Trouvere_Troubadour_pAtk_sMatk'
  | 'Arclouse Dash'
  | 'Mystic Symphony'
  | 'Two Hand Defending'
  | 'Axe Stomp'
  | 'Rush Quake'
  | '_Biolo_Monster_List'
  | '_Meister_Quake'
  | '_Meister_Rush'
  | '_Meister_ABR_List'
  | 'March of Prontera'
  | 'Arm Cannon'
  | 'Arrow Storm'
  | 'Arrow Vulcan'
  | 'Asir Runestone'
  | 'Assumptio'
  | 'Attack Stance'
  | 'Aura Blade'
  | 'Framen'
  | 'Geffenia Nocturne'
  | 'Arbitrium'
  | 'Auto Guard'
  | 'Kiling Cloud'
  | 'Auto Spell'
  | 'Axe Boomerang'
  | 'Axe Mastery'
  | 'Axe Tornado'
  | 'Back Stab'
  | 'Banishing Point'
  | 'Bash'
  | 'Earth Spike'
  | 'Basilica'
  | 'Beast Bane'
  | 'Bio Cannibalize'
  | 'Blaze Kick'
  | 'Blessing of Moon'
  | 'Blessing of Star'
  | 'Blessing of Sun'
  | 'Bowling Bash'
  | 'Break Through'
  | 'Bunch of Shrimp'
  | 'Calamity Gale'
  | 'Camouflage'
  | 'Cannon Spear'
  | 'Cantocandidus'
  | 'Cart Boost'
  | 'Cart Cannon'
  | 'Cart Remodeling'
  | 'Cart Tornado'
  | 'Cart Weight'
  | 'Catnip Meteor'
  | 'Cavalier Mastery'
  | 'Chain Action'
  | 'Chain Combo'
  | 'Chain Lightning'
  | 'Charm'
  | 'Chattering'
  | 'Circling Nature'
  | 'Clashing Spiral'
  | 'Clementia'
  | 'Cloaking Exceed'
  | 'Cold Bolt'
  | 'Comet Amp'
  | 'Comet'
  | 'Counter Slash'
  | 'Crazy Uproar'
  | 'Crescive Bolt'
  | 'Crimson Marker'
  | 'Crimson Rock'
  | 'Cross Impact'
  | 'Cross Rain'
  | 'Cross Ripper Slasher'
  | 'Cross Slash'
  | 'Cross Wound'
  | 'Current HP'
  | 'Current SP'
  | 'Curse Explosion'
  | 'Dagger Throwing Practice'
  | 'Dance With Wug'
  | 'Dancing Lesson'
  | 'Dark Claw'
  | 'Dark Illusion'
  | 'Dart Arrow'
  | 'Death Bound'
  | 'Demon Bane'
  | 'Desperado'
  | 'Diamond Dust'
  | 'Distorted Crescent'
  | 'Divine Protection'
  | 'Dodge'
  | 'Double Attack'
  | 'Double Strafe'
  | 'Dragon Breath - WATER'
  | 'Dragon Breath'
  | 'Dragon Combo'
  | 'Dragon Howling'
  | 'Dragon Tail'
  | 'Dragon Training'
  | 'Dragonic Aura'
  | 'Dragonology'
  | 'Drain Life'
  | 'Earth Drive'
  | 'Earth Grave'
  | 'Earth Shaker'
  | 'Earth Strain'
  | 'Enchant Blade'
  | 'Enchant Deadly Poison'
  | 'Esma'
  | 'Espa'
  | 'Eswhoo'
  | 'Evil Soul Curse'
  | 'Expiatio'
  | 'Exploding Dragon'
  | 'Fairy Soul'
  | 'Faith'
  | 'Falcon Eyes'
  | 'Fallen Empire'
  | 'Falling Stars'
  | 'Fatal Manace'
  | 'Fear Breeze'
  | 'Feint Bomb'
  | 'Fire Bolt'
  | 'Fire Dance'
  | 'Fire Earth Research'
  | 'Fire Rain'
  | 'First Wind'
  | 'Fist Spell'
  | 'Flame Launcher'
  | 'Flaming Petals'
  | 'Flash Combo'
  | 'Focused Arrow Strike'
  | 'Foresight'
  | 'Frash Shrimp'
  | 'Freezing Spear'
  | 'Freezing Spell'
  | 'Frost Misty'
  | 'Frost Weapon'
  | 'Full Moon Kick'
  | 'Fusion of Sun, Moon and Star'
  | 'Gale Storm'
  | 'Genesis Ray'
  | 'Gentle Touch - Alive'
  | 'Gentle Touch - Opposite'
  | 'Gloria Domini'
  | 'Grand Cross'
  | 'Grand Judgement'
  | 'Gravitational Field'
  | 'Great Echo'
  | 'Gunslinger Mine'
  | 'Hack and Slasher'
  | 'Happy Break'
  | 'Heal'
  | 'Hell Gate'
  | 'Hell Inferno'
  | 'Hiding'
  | 'Hilt Binding'
  | 'Hiss'
  | 'Holy Light'
  | 'Holy Shield'
  | 'Hot Barrel'
  | 'Hundred Spears'
  | 'Ignition Break'
  | 'Illusion - Bewitch'
  | 'Illusion - Death'
  | 'Illusion - Shadow'
  | 'Illusion - Shock'
  | 'Impositio Manus'
  | 'Improve Concentration'
  | 'Improve Dodge'
  | 'Increase HP Recovery'
  | 'Increase SP Recovery'
  | 'Indulge'
  | 'Inspiration'
  | 'Intensification'
  | 'Intimidate'
  | 'Iron Hand'
  | 'Jack Frost'
  | 'Judex'
  | 'Kaahi'
  | 'Katar Mastery'
  | 'Knowledge of Sun Moon and Star'
  | 'Knowledge of Sun, Moon and Star'
  | 'Knuckle Arrow'
  | 'Knuckle Boost'
  | 'Kunai Explosion'
  | 'Kunai Splash'
  | 'Kyrie Eleison'
  | 'Land Protector'
  | 'Laudaagnus'
  | 'Lava Flow'
  | 'Learning Potion'
  | 'Lefthand Mastery'
  | 'Lesson'
  | 'Lightening Bolt'
  | 'Lightning Loader'
  | 'Lightning Ride'
  | 'Lion Howling'
  | 'Lord of Vermilion'
  | 'Lunar Luminance'
  | 'Lunatic Carrot Beat'
  | 'Lux Anima Runestone'
  | 'Mace Mastery'
  | 'Madness Crusher'
  | 'Madogear License'
  | 'Maelstrom'
  | 'Magnificat'
  | 'Magnum Break'
  | 'Magnus Exorcismus'
  | 'Main Ranger'
  | 'Mammonite'
  | 'Mandragora Howling'
  | 'Meditation'
  | 'Meow Meow'
  | 'Metalic Sound'
  | 'Meteor Assault'
  | 'Meteor Storm'
  | 'Moon Slasher'
  | 'Moonlight Fantasy'
  | 'Moonlight Serenade'
  | 'Musical Lesson'
  | 'Musical Strike'
  | 'Mystical Amplification'
  | 'Napalm Vulcan'
  | 'Neutral Barrier'
  | 'New Moon Kick'
  | 'New Poison Research'
  | 'Ninja Aura'
  | 'Ninja Mastery'
  | 'No Limits'
  | 'Nyang Grass'
  | 'Offertorium'
  | 'On Magogear'
  | 'Over Brand'
  | 'Overslash'
  | 'Peaceful Break'
  | 'Picky Peck'
  | 'Piety'
  | 'Pile Bunker'
  | 'Plagiarism'
  | 'Platinum Altar'
  | 'Poison Burst'
  | 'Poisonous Weapon'
  | 'Power Maximize'
  | 'Power of Flock'
  | 'Power of Land'
  | 'Power of Life'
  | 'Power of Sea'
  | 'Power Swing'
  | 'Power Thrust'
  | 'Power'
  | 'Preserve'
  | 'Psychic Wave'
  | 'Pure Soul'
  | 'Pyroclastic'
  | 'Radius'
  | 'Raid'
  | 'Rampage Blast'
  | 'Recognized Spell'
  | 'Released'
  | 'Reproduce'
  | 'Reverberation'
  | 'Ride Dragon'
  | 'Ride Peco'
  | 'Righthand Mastery'
  | 'Rising Dragon'
  | 'Rolling Cutter'
  | 'Round Trip'
  | 'Run'
  | 'Rune Mastery'
  | 'Rush To Windmill'
  | 'Safety Wall'
  | 'Scratch'
  | 'Seismic Weapon'
  | 'Servant Weapon'
  | 'Seven Wind'
  | 'Severe Rainstorm'
  | 'Shadow Formation'
  | 'Shadow Sense'
  | 'Shadow Spell'
  | 'Shadow Warrior'
  | 'Shatter Storm'
  | 'Shield Chain'
  | 'Shield Mastery'
  | 'Shield Press'
  | 'Shield Shooting'
  | 'Shield Spell'
  | 'Silvervine Root Twist'
  | 'Silvervine Stem Spear'
  | 'Single Action'
  | 'Frenzy Shot'
  | 'Skin Tempering'
  | 'Sky Blow'
  | 'Snake Eyes'
  | 'Snatcher'
  | 'Divulio'
  | 'Conflagration'
  | 'Ardor'
  | 'Lightning Land'
  | 'Terra Drive'
  | 'Procella'
  | 'Terramotus'
  | 'Venom Swamp'
  | 'Serpens'
  | 'Spell Enchanting'
  | 'Elemental Spirit Mastery'
  | 'Elemental Buster'
  | '_ElementalMaster_spirit'
  | 'Magic Book Mastery'
  | 'Strip Shadow'
  | 'Deft Stab'
  | 'Chain Reaction Shot'
  | 'Magic Sword Mastery'
  | 'Abyss Slayer'
  | 'Omega Abyss Strike'
  | 'Snow Flake Draft'
  | 'Solar Explosion'
  | 'Solar Luminance'
  | 'Solar Stance'
  | 'Song Of Mana'
  | 'Sonic Wave'
  | 'Soul Vulcan Strike'
  | 'Mystery Illusion'
  | 'Floral Flare Road'
  | 'Rain of Crystal'
  | 'Tornado Storm'
  | 'Stratum Tremor'
  | 'Crimson Arrow'
  | 'Climax'
  | 'Frozen Slash'
  | 'Storm Cannon'
  | 'Rock Down'
  | 'Diamond Storm'
  | 'Astral Strike'
  | 'Two hand Staff Mastery'
  | 'Soul Cutter'
  | 'Soul Destroyer'
  | 'Soul Drain'
  | 'Soul Expansion'
  | 'Soul'
  | 'Abyss Dagger'
  | 'Unlucky Rush'
  | 'Dagger & Bow Mastery'
  | 'Will of Faith'
  | 'Petitio'
  | 'Shadow Stab'
  | 'Religio'
  | '_Religio_Benedictum'
  | '_3Faith'
  | 'First Brand'
  | 'Second Faith'
  | 'Third Punish'
  | 'Second Judgement'
  | 'Third Consecration'
  | 'Second Flame'
  | 'Third Flame Bomb'
  | 'Oleum Sanctum'
  | 'Explosion Blaster'
  | 'Eternal Slash'
  | 'Shadow Exceed'
  | 'Savage Impact'
  | 'Impact Crater'
  | 'Enchanting Shadow'
  | 'Shadow Wound'
  | 'Potent Venom'
  | 'Fatal Shadow Claw'
  | 'Massive Flame Blaster'
  | 'Benedictum'
  | 'Argutus Vita'
  | 'Argutus Telum'
  | '_Argutus Vita_Telum'
  | 'Presens Acies'
  | 'Spear & Sword Mastery'
  | 'Mace & Book Mastery'
  | 'Spear Dynamo'
  | 'Spear Mastery'
  | 'Spear Quicken'
  | 'Spin Count'
  | 'Spirit of Savage'
  | 'Spore Explosion'
  | 'Sprit Of Life'
  | 'Steel Crow'
  | 'Stellar Luminance'
  | 'Stellar Stance'
  | 'Storm Slash'
  | 'Striking'
  | 'Swing Dance'
  | 'Swirling Petal'
  | 'Sword Mastery'
  | 'Tetra Vortex'
  | 'Throw Huuma Shuriken'
  | 'Tiger Cannon'
  | 'Total Soul'
  | 'Total Spirit'
  | 'Transcendence'
  | 'Trap Research'
  | 'Triangle Shot'
  | 'Turisus Runestone'
  | 'Two hand Quicken'
  | 'Two-Handed Sword Mastery'
  | 'Urgent Escape'
  | 'Vanishing Buster'
  | 'Varetyr Spear'
  | 'Venom Impression'
  | 'Vigor condensation'
  | 'Vigor Explosion'
  | 'Vulcan Arm'
  | 'Weapon Blocking'
  | 'Weapon Perfection'
  | 'Weaponry Research'
  | 'Wind Blade'
  | 'Wind Cutter'
  | 'Wind Walk'
  | 'Wooden Fairy'
  | 'Wounding Shot'
  | 'Wrath of'
  | 'Wug Rider'
  | 'Wug Strike'
  | "Bragi's Poem"
  | "Frigg's Song"
  | "God's Hammer"
  | "Heaven's Drive"
  | "Lerad's Dew"
  | "Odin's Power"
  | "Owl's Eye"
  | "Rich's Coin"
  | "Vulture's Eye";
