import { agi, dex, int, str, vit } from "./_basic";

export const varmundt3 = [
  'Barmund_Pow1',
  'Barmund_Pow2',
  'Barmund_Pow3',
  'Barmund_Spl1',
  'Barmund_Spl2',
  'Barmund_Spl3',
  'Barmund_Con1',
  'Barmund_Con2',
  'Barmund_Con3',
  'Barmund_Crt1',
  'Barmund_Crt2',
  'Barmund_Crt3',
  // 'Barmund_Wis1',
  // 'Barmund_Wis2',
  // 'Barmund_Wis3',
  'Barmund_Sta1',
  'Barmund_Sta2',
  'Barmund_Sta3',
];

export const varmundt4 = [
  ...str(3, 5),
  ...int(3, 5),
  ...dex(2, 4),
  ...agi(3, 5),
  ...vit(3, 5),
]

export const varmundtAcc4 = [
  'Ba_Pow1',
  'Ba_Pow2',
  'Ba_Pow3',
  'Ba_Pow4',
  'Ba_Pow5',
  'Ba_Con1',
  'Ba_Con2',
  'Ba_Con3',
  'Ba_Con4',
  'Ba_Con5',
  'Ba_Crt1',
  'Ba_Crt2',
  'Ba_Crt3',
  'Ba_Crt4',
  'Ba_Crt5',
  'Ba_Sta1',
  'Ba_Sta2',
  'Ba_Sta3',
  'Ba_Sta4',
  'Ba_Sta5',
  'Ba_Spl1',
  'Ba_Spl2',
  'Ba_Spl3',
  'Ba_Spl4',
  'Ba_Spl5',
  'Ba_Wis1',
  'Ba_Wis2',
  'Ba_Wis3',
  'Ba_Wis4',
  'Ba_Wis5',
]
export const varmundtAcc3 = [
  'Ba_Stead1',
  'Ba_Stead2',
  'Ba_Stead3',
  'Ba_Stead4',
  'Ba_Stead5',
  'Ba_Tenacity1',
  'Ba_Tenacity2',
  'Ba_Tenacity3',
  'Ba_Tenacity4',
  'Ba_Tenacity5',
  'Ba_Intelligence1',
  'Ba_Intelligence2',
  'Ba_Intelligence3',
  'Ba_Intelligence4',
  'Ba_Intelligence5',
  'Ba_focus1',
  'Ba_focus2',
  'Ba_focus3',
  'Ba_focus4',
  'Ba_focus5',
  'Ba_Agility1',
  'Ba_Agility2',
  'Ba_Agility3',
  'Ba_Agility4',
  'Ba_Agility5',
  'Ba_Mental1',
  'Ba_Mental2',
  'Ba_Mental3',
  'Ba_Mental4',
  'Ba_Mental5',
]

export const varmundtHiAcc2 = [
  "Bio_Jam_Df1",
  "Bio_Jam_Df2",
  "Bio_Jam_Df3",
  "Bio_Jam_Es1",
  "Bio_Jam_Es2",
  "Bio_Jam_Es3",
  "Bio_Jam_Vl1",
  "Bio_Jam_Vl2",
  "Bio_Jam_Vl3",
  "Bio_Jam_Eq1",
  "Bio_Jam_Eq2",
  "Bio_Jam_Eq3",
  "Bio_Jam_Hd1",
  "Bio_Jam_Hd2",
  "Bio_Jam_Hd3",
  "Bio_Jam_Normal",
  "Bio_Jam_Boss",
]