const validBonus = [
  'Acid Bomb',
  'Acid Terror',
  'Adoramus',
  'Aimed Bolt',
  'Anti-Material Blast',
  'Arm Cannon',
  'Arrow Shower',
  'Arrow Storm',
  'Arrow Vulcan',
  'Axe Boomerang',
  'Axe Tornado',
  'Back Stab',
  'Banishing Point',
  'Blaze Kick',
  'Blitz Beat',
  'Bomb Cluster',
  'Bowling Bash',
  'Brandish Spear',
  'Burst Attack',
  'Cannon Spear',
  'Cart Boost',
  'Cart Cannon',
  'Cart Revolution',
  'Cart Termination',
  'Cart Tornado',
  'Catnip Meteor',
  'Chain Combo',
  'Chain Crush Combo',
  'Chain Lightning',
  'Chattering',
  'Clashing Spiral',
  'Claymore Trap',
  'Cold Bolt',
  'Cold Slower',
  'Combo Finish',
  'Comet',
  'Counter Slash',
  'Crazy Weed',
  'Crescive Bolt',
  'cri_race_demon',
  'cri_race_dragon',
  'cri_race_fish',
  'cri_race_insect',
  'cri_race_undead',
  'Crimson Marker',
  'Crimson Rock',
  'Cross Impact',
  'Cross Ripper Slasher',
  'Cross Slash',
  'Curse Explosion',
  'Dark Claw',
  'Dark Illusion',
  'Dart Arrow',
  'Desperado',
  'Diamond Dust',
  'dmg__Lucifer Morocc',
  'Double Strafe',
  'Dragon Breath - WATER',
  'Dragon Breath',
  'Dragon Combo',
  'Dragon Tail',
  'Drain Life',
  'Duple Light',
  'Earth Drive',
  'Earth Grave',
  'Earth Shaker',
  'Earth Spike',
  'Earth Strain',
  'Envenom',
  'Esma',
  'Espa',
  'Eswhoo',
  'Evil Soul Curse',
  'Exploding Dragon',
  'Fallen Empire',
  'Falling Stars',
  'Fatal Manace',
  'Feint Bomb',
  'Finger Offensive',
  'Fire Ball',
  'Fire Bolt',
  'Fire Dance',
  'Fire Pillar',
  'Fire Rain',
  'Firewall',
  'First Wind',
  'Flame Launcher',
  'Flaming Petals',
  'Flash Combo',
  'Flash Kick',
  'Focused Arrow Strike',
  'Freezing Spear',
  'Frost Misty',
  'Full Blast',
  'Full Moon Kick',
  'Genesis Ray',
  'Gloria Domini',
  'Grand Cross',
  'Gravitational Field',
  'Great Echo',
  'Grimtooth',
  'Hell Gate',
  'Hell Inferno',
  'Hell Plant',
  'Hiss',
  'Holy Cross',
  'Holy Light',
  'Hot Barrel',
  'Howling Mine',
  'Hundred Spears',
  'Ignition Break',
  'Infiltration',
  'Jack Frost',
  'Judex',
  'Jupitel Thunder',
  'Killing Cloud',
  'Knuckle Arrow',
  'Knuckle Boost',
  'Kunai Explosion',
  'Kunai Splash',
  'Land Mine',
  'Lava Flow',
  'Lightening Bolt',
  'Lightning Ride',
  'Lion Howling',
  'Lord of Vermilion',
  'Lucky Cast',
  'Lunatic Carrot Beat',
  'Magnum Break',
  'Magnus Exorcismus',
  'Mammonite',
  'Mandragora Howling',
  'Masquerade-Enervation',
  'Masquerade-Groomy',
  'Masquerade-Weakness',
  'Mass Spiral',
  'Metalic Sound',
  'Meteor Assault',
  'Meteor Storm',
  'Musical Strike',
  'Mystical Amplification',
  'Napalm Beat',
  'Napalm Vulcan',
  'New Moon Kick',
  'No Limits',
  'Nuckle Boost',
  'Nyang Grass',
  'Oratio',
  'Over Brand',
  'Picky Peck',
  'Pierce',
  'Pile Bunker',
  'Poison Burst',
  'Power Absorb',
  'Power Swing',
  'Psychic Wave',
  'Quick Draw Shot',
  'Raid',
  'Rampage Blast',
  'Reverberation',
  'Rolling Cutter',
  'Round Trip',
  'Savage Of Spirit',
  'Scar of Tarou',
  'Severe Rainstorm',
  'Shatter Storm',
  'Shield Boomerang',
  'Shield Chain',
  'Shield Press',
  'Sightless Mind',
  'Silvervine Stem Spear',
  'Sky Blow',
  'Slinging Arrow',
  'Slug Shot',
  'Snow Flake Draft',
  'Solar Explosion',
  'Sonic Blow',
  'Sonic Wave',
  'Soul Destroyer',
  'Soul Expansion',
  'Soul Harvest',
  'Soul Strike',
  'Spore Explosion',
  'Spread Shot',
  'Sprit Of Savage',
  'Storm Blast',
  'Storm Gust',
  'Suicidal Destruction',
  'Swirling Petal',
  'Tasty Shrimp Party',
  'Tetra Vortex',
  'Throw Huuma Shuriken',
  'Throw Kunai',
  'Thunderstorm',
  'Tiger Cannon',
  'Tornado Axe',
  'Triangle Shot',
  'Turn Undead',
  'Urgent Escape',
  'Vanishing Buster',
  'Varetyr Spear',
  'Vulcan Arm',
  'Warmer',
  'Water Insignia',
  'Wind Blade',
  'Wind Cutter',
  'Wug Strike',
  "God's Hammer",
  "Heaven's Drive",
  "Rich's Coin",
  'Gale Storm',
];
export const validBonusSet = new Set(validBonus);
